spin_manifest_version = "1"
authors = ["Dejan Budimir <dejbug@users.noreply.github.com>"]
description = "Syndication for sites that don't provide it."
name = "atoms2"
trigger = { type = "http", base = "/" }
version = "0.1.1"

[[component]]
id = "ibtimes"
source = "ibtimes.wasm"
environment = { RATE = "3600" }
key_value_stores = [ "default" ]
allowed_http_hosts = [ "https://www.ibtimes.com" ]

[component.trigger]
route = "/ibtimes"

[component.build]
command = "spin py2wasm ibtimes -o ibtimes.wasm"
watch = ["ibtimes.py", "Store.py", "fetch.py", "abs.py", "Pipfile"]


[[component]]
id = "aldaily"
source = "aldaily.wasm"
environment = { RATE = "3600" }
key_value_stores = [ "default" ]
allowed_http_hosts = [ "https://www.aldaily.com" ]

[component.trigger]
route = "/aldaily"

[component.build]
command = "spin py2wasm aldaily -o aldaily.wasm"
watch = ["aldaily.py", "Store.py", "fetch.py", "Pipfile"]


[[component]]
id = "weforum"
source = "weforum.wasm"
environment = { RATE = "3600" }
key_value_stores = [ "default" ]
allowed_http_hosts = [ "https://www.weforum.org" ]

[component.trigger]
route = "/weforum"

[component.build]
command = "spin py2wasm weforum -o weforum.wasm"
watch = ["weforum.py", "Store.py", "fetch.py", "Pipfile"]
