spin_manifest_version = "1"
authors = ["Dejan Budimir <dejbug@users.noreply.github.com>"]
description = "Hand-crafted syndication for sites that don't provide it."
name = "atoms"
trigger = { type = "http", base = "/" }
version = "0.3.2"

[[component]]
id = "app"
source = "app.wasm"
environment = { RATE = "3600" }
key_value_stores = [ "default" ]
allowed_http_hosts = [ "https://www.ibtimes.com", "https://www.aldaily.com", "https://www.weforum.org" ]

[component.trigger]
route = "/..."

[component.build]
command = "spin py2wasm app -o app.wasm"
