spin_manifest_version = "1"
authors = ["Dejan Budimir <dejbug@users.noreply.github.com>"]
description = "Syndication for sites that don't provide it."
name = "atoms2"
trigger = { type = "http", base = "/" }
version = "0.2.0"

[[component]]
id = "app"
source = "app.wasm"
environment = { RATE = "3600" }
key_value_stores = [ "default" ]
allowed_http_hosts = [ "https://www.ibtimes.com", "https://www.aldaily.com", "https://www.weforum.org" ]

[component.trigger]
route = "/..."

[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "ibtimes.py", "aldaily.py", "weforum.py", "Store.py", "fetch.py", "abs.py", "Pipfile"]
